/*
 * Assembles agentrules/agentinstructions.md from the section and command
 * fragments. Stamps the managed block with INSTRUCTIONS_VERSION (see below) so
 * the extension can auto-refresh user copies whenever the docs change.
 *
 * Run via `npm run build:agent-docs` (called automatically by `npm run compile`).
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const AGENT_DIR = path.join(ROOT, 'agentrules');
const SECTIONS_DIR = path.join(AGENT_DIR, 'sections');
const COMMANDS_DIR = path.join(AGENT_DIR, 'commands');
const OUTPUT = path.join(AGENT_DIR, 'agentinstructions.md');

// Revision of the generated instruction docs. This is INTENTIONALLY decoupled
// from the HTTP protocol version (src/agent/portFile.ts -> AGENT_API_VERSION):
// the managed block in users' instruction files is refreshed whenever this
// number increases, so bump it on ANY content change (wording, fixes, new
// sections) — even when the wire protocol is unchanged. The marker is still
// emitted as `apiVersion=N` for backward compatibility with files already
// stamped by older builds (the extension's refresh regex expects that token).
//   v2 -> v3: #141 typo fixes, import-vs-rename guidance, endpoint-discovery
//             algorithm, dual-transport migration notes.
//   v3 -> v4: new commands (get_record, delete_record, create_application,
//             add_column, get_served_url, navigate_and_screenshot,
//             rest_request); await:true write confirmation on update/create.
//   v4 -> v5: run_background_script + delete_application (background-script
//             cascade), screenshot exactUrl strict targeting + structured
//             E_SCREENSHOT_PERMISSION with one auto-retry.
//   v5 -> v6: live form / page control via the g_form bridge (navigate,
//             set_field, get_form_state, run_ui_action, click_element).
const INSTRUCTIONS_VERSION = 6;

// Ordered list of commands. Entries missing a .md file are skipped with a
// warning so CI stays green while docs catch up.
const COMMAND_ORDER = [
	// connection / state
	'check_connection',
	'get_instance_info',
	'get_sync_status',
	'sync_now',
	'get_last_error',
	'clear_last_error',
	// records (write)
	'update_record',
	'update_record_batch',
	'create_artifact',
	'delete_record',
	// scoped-app ergonomics
	'create_application',
	'add_column',
	'delete_application',
	// records (read)
	'get_record',
	'get_table_metadata',
	'check_name_exists_remote',
	// queries
	'query_records',
	'get_parent_options',
	// generic passthrough / escape hatches
	'rest_request',
	'run_background_script',
	// file-system helpers
	'list_tables',
	'list_artifacts',
	'check_name_exists',
	'get_file_structure',
	'validate_path',
	// browser helpers
	'open_in_browser',
	'get_served_url',
	'refresh_preview',
	'take_screenshot',
	'navigate_and_screenshot',
	'run_slash_command',
	'activate_tab',
	'switch_context',
	'upload_attachment',
	// live form / page control (g_form bridge)
	'navigate',
	'set_field',
	'get_form_state',
	'run_ui_action',
	'click_element',
];

// Sections are assembled in filename-sorted order. Appendix (>= 80-) is
// appended AFTER the commands block.
const APPENDIX_THRESHOLD = 80;

function readSorted(dir: string): Array<{ name: string; body: string }> {
	if (!fs.existsSync(dir)) return [];
	return fs.readdirSync(dir)
		.filter((f) => f.endsWith('.md'))
		.sort()
		.map((name) => ({ name, body: fs.readFileSync(path.join(dir, name), 'utf8') }));
}

function sectionOrdinal(name: string): number {
	const m = /^(\d+)/.exec(name);
	return m ? parseInt(m[1], 10) : 999;
}

function main() {
	const sections = readSorted(SECTIONS_DIR);
	if (sections.length === 0) {
		console.error(`[build-agent-docs] no section fragments found in ${SECTIONS_DIR}`);
		process.exit(1);
	}

	const pre = sections.filter((s) => sectionOrdinal(s.name) < APPENDIX_THRESHOLD);
	const appendix = sections.filter((s) => sectionOrdinal(s.name) >= APPENDIX_THRESHOLD);

	const commandBlocks: string[] = [];
	for (const cmd of COMMAND_ORDER) {
		const p = path.join(COMMANDS_DIR, `${cmd}.md`);
		if (!fs.existsSync(p)) {
			console.warn(`[build-agent-docs] missing command doc: ${cmd}.md`);
			continue;
		}
		commandBlocks.push(fs.readFileSync(p, 'utf8').trimEnd());
	}

	// Sanity: surface any command .md files not listed in COMMAND_ORDER.
	if (fs.existsSync(COMMANDS_DIR)) {
		const known = new Set(COMMAND_ORDER.map((c) => `${c}.md`));
		for (const f of fs.readdirSync(COMMANDS_DIR)) {
			if (f.endsWith('.md') && !known.has(f)) {
				console.warn(`[build-agent-docs] command doc not in COMMAND_ORDER: ${f}`);
			}
		}
	}

	const header = [
		`<!-- SN-SCRIPTSYNC:BEGIN apiVersion=${INSTRUCTIONS_VERSION} -->`,
		`<!-- apiVersion: ${INSTRUCTIONS_VERSION} -->`,
		`<!-- generated by scripts/build-agent-docs.ts — edit fragments in agentrules/{sections,commands}/ -->`,
		'',
	].join('\n');

	const body = [
		header,
		pre.map((s) => s.body.trimEnd()).join('\n\n'),
		'## Available Commands',
		'',
		commandBlocks.join('\n\n'),
		appendix.map((s) => s.body.trimEnd()).join('\n\n'),
	].filter(Boolean).join('\n\n') + '\n';

	// Everything between the BEGIN/END markers is owned by the extension and is
	// refreshed in place; user content outside the markers is preserved.
	const output = body + '\n<!-- SN-SCRIPTSYNC:END -->\n';

	fs.writeFileSync(OUTPUT, output);
	console.log(`[build-agent-docs] wrote ${OUTPUT} (instructionsVersion=${INSTRUCTIONS_VERSION}, ${pre.length + appendix.length} sections, ${commandBlocks.length} commands)`);
}

main();
